### ISSUE TITLE
cannot login with a hifi plus account

### ISSUE THREAD

**Issue by kingdariud01** [ebb-earl-co/tidal-wave#10]
cannot login with a hifi plus account. when i copy and paste the activation link into a browser  i get the following message : FileNotFoundError: [WinError 2] The system cannot find the file specified. please help

**Comment by ebb-earl-co** [comment]
Interesting. I haven't developed on Windows so I will have to do some testing.

Does the script's process break when you copy the activation link? Or after you sign in on the webpage? Or something else...

**Comment by kingdariud01** [comment]
The breaks when I copy a link for download. If the link is low quality, it will down but if it is lossless or hires it will break. You said you didn’t develop on windows does it mean that the script isn’t compatible to windows machines?Sent from my iPhoneOn Dec 19, 2023, at 8:04 PM, Colin Coe ***@***.***> wrote:﻿
Interesting. I haven't developed on Windows so I will have to do some testing.
Does the script's process break when you copy the activation link? Or after you sign in on the webpage? Or something else...

**Comment by ebb-earl-co** [comment]
Interesting. I've just pulled up a Windows system, and I am running through the whole flow.

**Note**: I am seeing the error that you're mentioning upon first run to create a Fire TV client. That error is just in the logs, and I will clean it up. I highlighted the link with my cursor, then did a control - C + control - V into my browser, and that was successful.

@kingdariud01 can you try version `2023.12.7` that is the newest release? *EDIT*: in fact, I've just compiled a `pyapp` binary for Windows: it's the one with .exe at the end. I've gotten it running on my Windows system as we speak

**Comment by kingdariud01** [comment]
I am sorry but the newest version did not work for me either. It returns the same error message as before. As far a the  exe file it  crashes at launch. I am running windows 11 may be my window version? Sent from my iPhoneOn Dec 19, 2023, at 9:28 PM, Colin Coe ***@***.***> wrote:﻿
Interesting. I've just pulled up a Windows system, and I am running through the whole flow.
Note: I am seeing the error that you're mentioning upon first run to create a Fire TV client. That error is just in the logs, and I will clean it up. I highlighted the link with my cursor, then did a control - C + control - V into my browser, and that was successful.
@kingdariud01 can you try version 2023.12.7 that is the newest release?

**Comment by ebb-earl-co** [comment]
@kingdariud01 is this the error that you're experiencing?
![image](https://github.com/ebb-earl-co/tidal-wave/assets/11299014/f25eedb8-0056-40f5-ad6c-5e7cd0791d98)

In this case, it's because of Windows security: by default, it doesn't allow scripts to be run without modifications. If you just want to be able to run the .exe or the Python scripts, you can run this in Powershell: 
```powershell
Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope CurrentUser
```

more information [here](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-7.4)

Separately, you might need to tell Windows that the .exe is allowed to be run: if you right-click on the file, you'll see the following dialog:
![image](https://github.com/ebb-earl-co/tidal-wave/assets/11299014/592ba9cc-0fff-4797-9e1b-fe171b1634f9)
You'll need to check the tick-box in the `Security` section, then apply.

If it's *not* that issue, can you send a screen shot of what the error is when you try to run either the Python package or the .exe?

**Comment by kingdariud01** [comment]
This is what I get when I run tidal-wave url. Thanks

**Comment by ebb-earl-co** [comment]
> This is what I get when I run tidal-wave url. Thanks

@kingdariud01 there's no image or other text after the first line. Maybe try to upload again?

**Comment by ebb-earl-co** [comment]
Closing this issue as it's been 2 weeks without further information.
