### ISSUE TITLE
Not Able To Download In Hi-Res FLAC

### ISSUE THREAD

**Issue by rajeshsahoo12** [ebb-earl-co/tidal-wave#25]
I am using latest binary of tidal-wave. Have downloaded many hi-res FLAC tracks / albums using access token from android device. There was no issue faced.

But when I try to download this album error comes. I have used below command to download the album & included --loglevel option to debug. Log shows that URL is invalid but when I open the same URL in browser they are opening.

**tidal-wave https://tidal.com/browse/album/66390838 --audio-format hires --loglevel debug**

![image](https://github.com/ebb-earl-co/tidal-wave/assets/54216637/f8a6bf7b-5428-4503-9ea5-667011a98872)

**tidal-wave https://tidal.com/browse/album/67006305 --audio-format hires --loglevel debug**

![image](https://github.com/ebb-earl-co/tidal-wave/assets/54216637/e6cbb94f-96a6-4e29-a657-a49e5f68f00f)

Error log is attached for further details.

Thanks 
[Error_Log.txt](https://github.com/ebb-earl-co/tidal-wave/files/13814274/Error_Log.txt)

**Comment by ebb-earl-co** [comment]
@Rajeshsahoo12 Based on the logs that you uploaded, the track that has caused an error is `'C:\\Users\\Rajesh Sahoo\\Music\\Pritam\\Ae Dil Hai Mushkil (Original Motion Picture Soundtrack) [66390838] [2016]\\01 - Ae Dil Hai Mushkil Title Track (From "Ae Dil Hai Mushkil") [HiRes].flac`: just looking at it, I believe that the error is caused by there being "" in the filename and that breaking the quoting of file names by `ffmpeg` on the command line.

For now, can you try the same album but in a different audio format? Maybe just `--audio-format low` for speed's sake, while I come up with an idea around track titles with "" in them.
