### ISSUE TITLE
Not Able To Parse Album Error

### ISSUE THREAD

**Issue by rajeshsahoo12** [ebb-earl-co/tidal-wave#46]
Hi,

As earlier this bug was fixed due to ALBUM ID length. But now on latest release 2024.1.8

Again this error came

tidal-wave https://tidal.com/browse/track/42298 --audio-format atmos
2024-01-11:18:12:22,451 CRITICAL [main.py:70] Cannot parse 'https://tidal.com/browse/track/42298' as a TIDAL album, artist, mix, playlist, track, or video URL

**Comment by ebb-earl-co** [comment]
@Rajeshsahoo12 thank you for having filed this issue. It's slightly different to the previous issue, as I had only changed the logic for albums in that fix. For now, you could download that album entirely instead of the track, but I will go ahead and make the changes to the track ID logic.

Side note: this album, and the track you've denoted, is not available in Dolby Atmos format. Just FYI

**Comment by ebb-earl-co** [comment]
@Rajeshsahoo12 this is fixed with #47 . The fix is available in version 2024.1.9

**Comment by rajeshsahoo12** [comment]
> thank you for having filed this issue. It's slightly different to the previous issue, as I had only changed the logic for albums in that fix. For now, you could download that album entirely instead of the track, but I will go ahead and make the changes to the track ID logic.

Ohhhh yeah I realized now that earlier fix was related to album id. I missed it. This time it was related to track id. Thanks for the fix so fast.

**Comment by rajeshsahoo12** [comment]
> Side note: this album, and the track you've denoted, is not available in Dolby Atmos format. Just FYI

Was just checking for whether this is available or not in atmos quality. But before I encountered error. So, just posted here. Thanks for info.
